appName: "$helmChartName"
replicaset: 1
image: mysql
tag: 8.0
containerPort: 3306
nodePort: "$NodePort"
domain: "$domainName"
secret:
  tls: "$helmChartName-tls"
env:
  database:
    DBname: MYSQL_DB
    db: "$DB_NAME"
    DBpassword: MYSQL_ROOT_PASSWORD
    password: "$DB_PASSWORD"
chart:
  name: "$helmChartName"